// import { Html } from "next/document"
import Head from "next/head"
import Header from "./Header"
import Footer from "./Footer"
const App = (props) => {
  const userData = props.userData
  return (
    <>
      <html lang="en">
        <Head>
          <title>EventGate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <Header userData={userData} />
          <div>
            {props.children}
          </div>
          <Footer />
        </body>
      </html>
    </>
  )
}

export default App